Update setup-rust-analyzer to handle status code
Signed-off-by: Yasha <yasuhiro.asaka@grauwoelfchen.net>

diff --git a/setup-rust-analyzer b/setup-rust-analyzer
--- a/setup-rust-analyzer
+++ b/setup-rust-analyzer
@@ -6,6 +6,7 @@ set -eux
 
 # e.g. setup-rust-analyzer 2022-10-17
 release="${1:-2022-10-17}"
+location="$HOME/.atelier/bin"
 
 toolchain="stable"
 platform="x86_64-unknown-linux-gnu"
@@ -16,9 +17,11 @@ name="rust-analyzer"
 repo_url="https://github.com/${organization}/${name}"
 download_url="${repo_url}/releases/download/${release}/${name}-${platform}.gz"
 
-location="$HOME/.atelier/bin"
-
-curl -sL $download_url -o $location/$name.gz
+result=$(curl -sL $download_url -o $location/$name.gz -w "%{http_code}")
+if [ "${result}" != "200" ]; then
+  echo "---> Not found :'("
+  exit 2
+fi
 gunzip $location/$name.gz
 
 chmod +x $location/$name
